version: "3.9"
services:
  db:
    image: library/postgres:14-alpine
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - app_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env.development
  web:
    env_file:
      - .env.development
    depends_on: 
      - db
    build: 
      args: 
        RAILS_ENV: development
volumes:
  app_postgres:
