version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /usr/bin/entrypoint.sh
    command: ["bundle", "exec", "puma" ,"-C" ,"config/puma.rb"]
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
volumes:
  app_redis:
