openapi: 3.0.0
info:
  version: 1.0.0
  title: Galaxia Backend API
  description: OpenAPI specification for the backend.
  contact:
    name: Ernest Nkansah-Badu
    email: ernest.nkansah-badu.19@ucl.ac.uk
    url: https://galaxia-js.web.app
  license:
    name: MIT
servers:
  - url: "https://galaxia-zoju.onrender.com/api/v1"
paths:
  /users/register:
    $ref: "./paths/user/register.yaml"
  /users/login:
    $ref: "./paths/user/login.yaml"

  /celestial/planets/{id}:
    $ref: "./paths/celestial/planet_fetch.yaml"
  /celestial/planets/:
    $ref: "./paths/celestial/planets.yaml"

  /celestial/stars/{id}:
    $ref: "./paths/celestial/star_fetch.yaml"
  /celestial/stars/:
    $ref: "./paths/celestial/stars.yaml"

  /celestial/moons/{id}:
    $ref: "./paths/celestial/moon_fetch.yaml"
  /celestial/moons/:
    $ref: "./paths/celestial/moons.yaml"

  /celestial/asteroid_belts/{id}:
    $ref: "./paths/celestial/asteroid_fetch.yaml"
  /celestial/asteroid_belts/:
    $ref: "./paths/celestial/asteroids.yaml"

  /simulations:
    $ref: "./paths/simulation/create_sim.yaml"

  /simulations/{id}:
    $ref: "./paths/simulation/simulation.yaml"
  /simulations/{id}/planets/{planet_id}:
    $ref: "./paths/simulation/planet.yaml"
  /simulations/{id}/planets/{planet_id}/moon/{moon_id}:
    $ref: "./paths/simulation/moon.yaml"
  /simulations/{id}/stars/{star_id}:
    $ref: "./paths/simulation/star.yaml"
  /simulations/{id}/asteroid_belts/{asteroid_belt_id}:
    $ref: "./paths/simulation/asteroid_belt.yaml"

  /simulations/all/preset:
    $ref: "./paths/simulation/get_preset_sims.yaml"
  /simulations/all/user:
    $ref: "./paths/simulation/get_user_created_sims.yaml"
  /simulations/by/{id}:
    $ref: "./paths/simulation/get_sims_by_user.yaml"

  /media/textures:
    $ref: "./paths/media/textures/all_textures.yaml"
  /media/textures/{id}:
    $ref: "./paths/media/textures/single_texture.yaml"
  /media/textures/all/planets:
    $ref: "./paths/media/textures/planet_textures.yaml"
  /media/textures/all/stars:
    $ref: "./paths/media/textures/star_textures.yaml"
  /media/textures/all/moons:
    $ref: "./paths/media/textures/moon_textures.yaml"

  /media/atmosphere_textures:
    $ref: "./paths/media/atmosphere_textures/all_atmosphere_textures.yaml"
  /media/atmosphere_textures/{id}:
    $ref: "./paths/media/atmosphere_textures/single_atmosphere_texture.yaml"
  /media/atmosphere_textures/all/planets:
    $ref: "./paths/media/atmosphere_textures/planet_atmosphere_textures.yaml"
  /media/atmosphere_textures/all/stars:
    $ref: "./paths/media/atmosphere_textures/star_atmosphere_textures.yaml"
  /media/atmosphere_textures/all/moons:
    $ref: "./paths/media/atmosphere_textures/moon_atmosphere_textures.yaml"

  /media/bump_maps:
    $ref: "./paths/media/bump_maps/all_bump_maps.yaml"
  /media/bump_maps/{id}:
    $ref: "./paths/media/bump_maps/single_bump_map.yaml"
  /media/bump_maps/all/planets:
    $ref: "./paths/media/bump_maps/planet_bump_maps.yaml"
  /media/bump_maps/all/stars:
    $ref: "./paths/media/bump_maps/star_bump_maps.yaml"
  /media/bump_maps/all/moons:
    $ref: "./paths/media/bump_maps/moon_bump_maps.yaml"

  /media/specular_maps:
    $ref: "./paths/media/specular_maps/all_specular_maps.yaml"
  /media/specular_maps/{id}:
    $ref: "./paths/media/specular_maps/single_specular_map.yaml"
  /media/specular_maps/all/planets:
    $ref: "./paths/media/specular_maps/planet_specular_maps.yaml"
  /media/specular_maps/all/stars:
    $ref: "./paths/media/specular_maps/star_specular_maps.yaml"
  /media/specular_maps/all/moons:
    $ref: "./paths/media/specular_maps/moon_specular_maps.yaml"

components:
  responses:
    UnauthorizedError:
      description: The user is not logged in
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnauthorizedError"
    BadRequestError:
      description: Action failed due to missing parameters in request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestErrorResponse"
    GenericError:
      description: A generic server side error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GenericErrorResponse"
    NotFoundError:
      description: Action failed as the requested resource could not be located
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GenericErrorResponse"
    UnprocessableEntityError:
      description: Action failed due to semantic issues with input
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GenericFieldErrorsResponse"
  schemas:
    $ref: "./schemas/_index.yaml"
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
